### ISSUE TITLE
log levels not working

### ISSUE THREAD

**Issue by justechn** [namshi/winston-graylog2#34]
According to your docs I should have access to the following log levels
emergency
alert
critical
error
warning
notice
info
debug

however it seems like only a couple of them are working.

if I try winston.warning('this is a test'); I get a fatal error. If I try winston.log('warning', 'this is a test'); it does not error, but it also does not log.

but if I do winston.debug('this is a test'); and winston.log('debug', 'this is a test'); it works fine.

What am I doing wrong?

I setup winston like this
```
var config = {
    name: 'Graylog',
    level: 'debug',
    silent: false,
    handleExceptions: true,
    prelog: function (msg) {
        return msg.trim();
    },
    graylog: {
        servers: [{host: '192.168.0.1', port: 12201}],
        hostname: 'server.lan',
        facility: 'Dialer List Definitions',
        bufferSize: 1400
    }
};

var winston = require('winston');
winston.add(require('winston-graylog2'), config);
```

**Comment by unlucio** [comment]
hi @justechn, can you post the stack trace from when you use `winston.warning('this is a test');`?

**Comment by justechn** [comment]
```
Error: No default engine was specified and no extension was provided.
    at new View (c:\projects\DialerListDefinitions\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (c:\projects\DialerListDefinitions\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (c:\projects\DialerListDefinitions\node_modules\express\lib\response.js:961:7)
    at c:\projects\DialerListDefinitions\app.js:47:9
    at Layer.handle_error (c:\projects\DialerListDefinitions\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:310:13)
    at c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:330:12)
    at next (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:271:10)
    at Layer.handle_error (c:\projects\DialerListDefinitions\node_modules\express\lib\router\layer.js:73:5)
    at trim_prefix (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:310:13)
    at c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:330:12)
    at next (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:271:10)
    at Layer.handle_error (c:\projects\DialerListDefinitions\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:310:13)
    at c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:330:12)
    at next (c:\projects\DialerListDefinitions\node_modules\express\lib\router\index.js:271:10)
```

**Comment by justechn** [comment]
ignore the stack trace. This was my fault. After fixing that I now get a message "[TypeError: undefined is not a function]" when trying to use winston.warning

**Comment by justechn** [comment]
nevermind, I found a different solution

**Comment by odino** [comment]
hey @justechn would you mind sharing the solution?

**Comment by justechn** [comment]
I am using a different graylog package
